More sql alchemy ported probes
ericvaandering/probes pull request #4
Opened 2020-08-19 22:57 UTC by FernandoGarzon

2020-08-21 15:19 UTC, ericvaandering requested changes

2020-08-21 15:19 UTC, ericvaandering commented on common/check_deletable_replicas
> +from rucio.db.sqla.constants import ReplicaState
What editor are you using? PyCharm has a very nice function called "organize imports" which groups things together, etc. If you don't have it don't worry, I will run this through it.

2020-08-21 15:19 UTC, ericvaandering commented on common/check_deletable_replicas
> -if __name__ == "__main__":
Please don't change this. If the original used a main() then keep it. If it didn't don't worry.

2020-08-21 15:19 UTC, ericvaandering commented on common/check_deletable_replicas
> +        print(a)
This should be removed in the final version

2020-08-21 15:19 UTC, ericvaandering commented on common/check_expired_locked_rules
> +# - Cedric Serfon, <cedric.serfon@cern.ch>, 2015. Eric Vaandering, <ewv@fnal.gov> and Fernando Garzon, <oscar.fernando.garzon.miguez@cern.ch>
Put each of us on a separate line with 2020 please

2020-08-21 15:19 UTC, ericvaandering commented on common/check_expired_locked_rules
> +        print(dids)
Not sure either of these print statements add anything.

2020-08-21 15:19 UTC, ericvaandering commented on common/check_ok_rules
> +#!/usr/bin/env python
In my version, check_not_OK_rules is now part of check_rule_counts. Does it make sense to move this in too?

2020-08-24 23:44 UTC, FernandoGarzon commented on common/check_deletable_replicas
> -if __name__ == "__main__":
Set back as original

2020-08-24 23:44 UTC, FernandoGarzon commented on common/check_deletable_replicas
> +from rucio.db.sqla.constants import ReplicaState
I'm using visual studio

2020-08-24 23:44 UTC, FernandoGarzon commented on common/check_ok_rules
> +#!/usr/bin/env python
Ok. Let me know if this needs to be removed.

2020-08-25 20:21 UTC, merged